### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by vjdaemp** [WillBrennan/SemanticSegmentation#24]
Hello @WillBrennan ,

I tried to train using my own data / annotation files, but received the following error:

```
python train.py --train /home/yoda/Development/sportModel/Training --val /home/yoda/Development/sportModel/Validation --model-tag segmentation_sport --model-type FCNResNet101
INFO:root:running training on cuda
INFO:root:creating dataset and data loaders
INFO:root:loaded 240 annotations from /home/yoda/Development/sportModel/Training
INFO:root:use augmentation: True
INFO:root:categories: ['baseball', 'golf_ball', 'basketball']
INFO:root:loaded 40 annotations from /home/yoda/Development/sportModel/Validation
INFO:root:use augmentation: False
INFO:root:categories: ['baseball', 'golf_ball', 'basketball']
INFO:root:creating dataloaders with 16 workers and a batch-size of 2
/home/yoda/anaconda3/envs/semantic_segmentation/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
INFO:root:creating FCNResNet101 and optimizer with initial lr of 0.0001
INFO:root:creating model with categories: ['baseball', 'golf_ball', 'basketball']
INFO:root:creating trainer and evaluator engines
Traceback (most recent call last):
  File "/home/yoda/Desktop/sport-segmentation/SemanticSegmentation/train.py", line 87, in <module>
    'IoU@0.3': IoUMetric(thresholded_transform(threshold=0.3)),
  File "/home/yoda/Desktop/sport-segmentation/SemanticSegmentation/semantic_segmentation/metrics.py", line 18, in __init__
    super().__init__(output_transform=output_transform, device=device)
  File "/home/yoda/anaconda3/envs/semantic_segmentation/lib/python3.9/site-packages/ignite/metrics/metric.py", line 224, in __init__
    if torch.device(device).type == "xla":
TypeError: Device() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (torch.device device)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (str type, int index)
```

Any idea on why this might be occurring and how to resolve? Thanks!

**Comment by amar-fayaz** [comment]
Hi @vjdaemp,
I have also ended up with the same issue. I know it's been a while since you put it, but did you end up solving this?

**Comment by WillBrennan** [comment]
Sorry; I lost complete track of this and didn't get a chance to look at it. Its likely a version issue; 

- can you run `conda env export` and submit it below? 
- Are you running a GPU and what value do you get when you run, 

```python
import torch 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"found {device}")
```

**Comment by amar-fayaz** [comment]
Hi @WillBrennan,
Thank you for the prompt reply.

I'm attaching the conda env at the bottom. It's pretty long with unnecessary packages that I dev with, so sorry in advance :).

I do have 2 GPUs connected to my system and I'm running by isolating it to 1 GPU (using CUDA_VISIBLE_DEVICES) and I do get "found cuda" when I run your code.

I temporarily fixed the issue above by editing
https://github.com/WillBrennan/SemanticSegmentation/blob/master/train.py#L85, both line 85 and 86 by passing 'cuda' into the ```IoUMetric`` initialization. But I'm not sure if it's the ideal solution.



```
name: semantic
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - asgiref=3.3.1=pyhd3eb1b0_0
  - astroid=2.5=py37h06a4308_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blosc=1.20.1=hd408876_0
  - brotli=1.0.9=he6710b0_2
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - charls=2.1.0=he6710b0_2
  - cloudpickle=1.6.0=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2021.1.1=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py37h295c915_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - django=3.1.6=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.69.1=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - imagecodecs=2021.1.11=py37h581e88b_1
  - imageio=2.9.0=py_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2020.2=254
  - ipykernel=6.2.0=py37h06a4308_1
  - ipython=7.27.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=5.7.0=pyhd3eb1b0_0
  - jedi=0.18.0=py37h06a4308_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.1=py37h2531618_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.5.2=py37h27cfd23_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=2.2.1=h2531618_0
  - libaec=1.0.4=he6710b0_1
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.2=h20c2e04_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-base=3.3.2=py37h817c723_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.4.3=py37h06a4308_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py37he98fc37_0
  - pip=20.3.3=py37h06a4308_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt_toolkit=3.0.17=hd3eb1b0_0
  - psycopg2=2.8.6=py37h3c74f83_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.7.1=py37h06a4308_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyyaml=5.4.1=py37h27cfd23_1
  - pyzmq=22.2.1=py37h295c915_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - scikit-image=0.17.2=py37hdf5156a_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.6.0=py37h91f5cce_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37h06a4308_0
  - shapely=1.7.1=py37h98ec03d_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py37h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.33.0=h62c20be_0
  - sqlparse=0.4.1=py_0
  - terminado=0.9.4=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.1.14=pyhd3eb1b0_1
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.2=py37h27cfd23_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h2531618_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - albumentations==1.1.0
    - amqp==5.0.5
    - apex==0.1
    - billiard==3.6.3.0
    - blessings==1.7
    - cachetools==4.2.1
    - celery==5.0.5
    - chardet==4.0.0
    - click==7.1.2
    - click-didyoumean==0.0.3
    - click-plugins==1.1.1
    - click-repl==0.1.6
    - colorama==0.4.4
    - colorlog==4.7.2
    - colormap==1.0.3
    - cython==0.29.21
    - django-celery-results==2.0.1
    - django-cors-headers==3.5.0
    - django-multiselectfield==0.1.12
    - django-mysql==3.11.1
    - djangorestframework==3.12.2
    - djangorestframework-api-key==2.0.0
    - easydev==0.11.0
    - easydict==1.9
    - et-xmlfile==1.0.1
    - filelock==3.3.0
    - filterpy==1.4.5
    - gdown==4.0.2
    - google-auth==1.25.0
    - google-auth-oauthlib==0.4.2
    - gpustat==0.6.0
    - grpcio==1.35.0
    - idna==2.10
    - ignite==1.1.0
    - importlib-metadata==3.4.0
    - jdcal==1.4.1
    - keyframe-conxai==0.0.1
    - kombu==5.0.2
    - lap==0.4.0
    - markdown==3.3.3
    - memory-profiler==0.58.0
    - mysqlclient==2.0.3
    - ninja==1.10.0.post2
    - nvidia-ml-py==11.450.51
    - nvidia-ml-py3==7.352.0
    - nvitop==0.3.5.2
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opencv-python-headless==4.5.4.60
    - openpyxl==3.0.6
    - pandas==1.2.2
    - patsy==0.5.1
    - pgmpy==0.1.13
    - plotly==4.14.3
    - prompt-toolkit==3.0.16
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pysocks==1.7.1
    - pytorch-ignite==0.4.7
    - qudida==0.0.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.7
    - schedule==1.1.0
    - statsmodels==0.12.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - tqdm==4.56.1
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - vine==5.0.0
    - werkzeug==1.0.1
    - xlrd==1.2.0
    - yacs==0.1.8
    - zipp==3.4.0
```

**Comment by WillBrennan** [comment]
Stale issue; resolving. Hope this is no longer an issue!
